### ISSUE TITLE
Product deletion blocked by modules/addons/cnicdns/hooks.php

### ISSUE THREAD

**Issue by an0nz** [centralnicgroup-opensource/rtldev-middleware-whmcs#241]
**Describe the bug**
When deleting any product in WHMCS an error is thrown by /modules/addons/cnicdns/hooks.php:119

**To Reproduce**
1. Install latest release of whmcs-cnic-bundle and activate the CNIC DNS module
2. Configure a DNS Zone Template in CNIC DNS (Step may not be required)
3. Create an empty product
4. Delete the empty product you just created
5. See error

**Expected behavior**
Product deletes without issue

**Error**
Error: Class 'CNIC\WHMCS\DNS\Product' not found in /home/user/public_html/modules/addons/cnicdns/hooks.php:119
Stack trace:
#0 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): WHMCS\Utility\SafeInclude::{closure}(Array)
#1 /home/user/public_html/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run('ProductDelete', Array, false)
#2 /home/user/public_html/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic('run', Array)
#3 /home/user/public_html/admin/configproducts.php(0): run_hook('ProductDelete', Array)
#4 {main}

**Context (please complete the following information):**
 - Device: Windows 10 with latest Chrome
 - OS: CloudLinux 8
 - Browser: Edge 109.0.1518.78
 - WHMCS Version 8.4.1
 - PHP Version 7.4.33
 - ISPAPI Registrar Module Version v16.15.0

**Comment by KaiSchwarz-cnic** [comment]
Thanks so much @an0nz for reporting. Do you mind giving [v16.15.1](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v16.15.1) a try?
